<a href="https://colab.research.google.com/github/Arachne0/Natrual_Language_Processing/blob/master/Feedforward_Neural_Network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
x = torch.tensor([2,1])
w1 = torch.tensor([[3,2,-4],[2,-3,1]])
b1 = 1
w2 = torch.tensor([[-1,1],[1,2],[3,1]])
b2 = -1

In [2]:
h_preact = torch.matmul(x,w1) + b1
h = torch.nn.functional.relu(h_preact)
y = torch.matmul(h,w2) + b2

h_preact

tensor([ 9,  2, -6])

In [3]:
h

tensor([9, 2, 0])

In [4]:
y

tensor([-8, 12])