<a href="https://colab.research.google.com/github/Arachne0/Natrual_Language_Processing/blob/master/SelfAttention.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
x = torch.tensor([ # 벡터 시퀀스 x 정의
    [1.0, 0.0, 1.0, 0.0],
    [0.0, 2.0, 0.0, 2.0],
    [1.0, 1.0, 1.0, 1.0],
])

w_query = torch.tensor([ # 쿼리 행렬 정의
    [1.0, 0.0, 1.0],
    [1.0, 0.0, 0.0],
    [0.0, 0.0, 1.0],
    [0.0, 1.0, 1.0],
])

w_key = torch.tensor([ # 키 행렬 정의
    [0.0, 0.0, 1.0],
    [1.0, 1.0, 0.0],
    [0.0, 1.0, 0.0],
    [1.0, 1.0, 0.0]
])

w_value = torch.tensor([ # 밸류 행렬 정의
    [0.0, 2.0, 0.0],
    [0.0, 3.0, 0.0],
    [1.0, 0.0, 3.0],
    [1.0, 1.0, 0.0]
])

In [2]:
# torch.matmul 는 행렬곱을 수행하는 함수
keys = torch.matmul(x, w_key)
querys = torch.matmul(x, w_query)
values = torch.matmul(x, w_value)

In [3]:
# 쿼리 벡터와 키 벡터를 행렬곱해서 어텐션 스코어를 만드는 과정. keys.T는 키 벡터들을 전치한 행렬
attn_scores = torch.matmul(querys, keys.T) 
attn_scores

tensor([[ 2.,  4.,  4.],
        [ 4., 16., 12.],
        [ 4., 12., 10.]])

In [4]:
# 앞 코드 결과에 키 벡터의 차원 수 제곱근으로 나눈 후 소프트맥스를 취하는 과정

import numpy as np
from torch.nn.functional import softmax
key_dim_sqrt = np.sqrt(keys.shape[-1])
attn_probs = softmax(attn_scores / key_dim_sqrt, dim = 1)
attn_probs

tensor([[1.3613e-01, 4.3194e-01, 4.3194e-01],
        [8.9045e-04, 9.0884e-01, 9.0267e-02],
        [7.4449e-03, 7.5471e-01, 2.3785e-01]])

In [5]:
# 셀프 어텐션은 학습 대상은 query, key , value를 만드는 가중치 행렬이다. 
# 이들은 태스크를 가장 잘 수행하는 방향으로 학습 과정에서 업데이트 된다.
weighted_values = torch.matmul(attn_probs, values)
weighted_values

tensor([[1.8639, 6.3194, 1.7042],
        [1.9991, 7.8141, 0.2735],
        [1.9926, 7.4796, 0.7359]])