<a href="https://colab.research.google.com/github/Arachne0/Natrual_Language_Processing/blob/master/Layer_Normalization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
input = torch.tensor([[1.0, 2.0, 3.0 ],[1.0, 1.0, 1.0]])
m = torch.nn.LayerNorm(input.shape[-1])
output = m(input)

In [2]:
output

tensor([[-1.2247,  0.0000,  1.2247],
        [ 0.0000,  0.0000,  0.0000]], grad_fn=<NativeLayerNormBackward0>)

In [7]:
m.weight 
# requires_grad 속성을 설정하면 autograd에게 모든 연산을 추적해야한다고 알려준다.

Parameter containing:
tensor([1., 1., 1.], requires_grad=True)

In [4]:
m.bias 
# m.weight와 m.bias는 β에 대응한다. pytorch의 LayerNorm 객체는 이 두 값을 각각 1,0으로 초기화한다.
# 학습 초기 레이어 정규화 수행은 배치 인스턴스의 평균을 빼고 표준편차로 나눈 결과에 1을 곱한후 0을 더한다는 이야기 

Parameter containing:
tensor([0., 0., 0.], requires_grad=True)